# Завдання 3

In [ ]:
import numpy as np
import pandas as pd

array = np.arange(15).reshape(3, 5)
transposed = array.T
reshaped = array.reshape(5, 3)

print("Вихідний масив 3 x 5:")
display(pd.DataFrame(array))
print("Транспонований масив:")
display(pd.DataFrame(transposed))
print("Масив після reshape(5, 3):")
display(pd.DataFrame(reshaped))

Вихідний масив 3 x 5:

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14

Транспонований масив:

   0  1   2
0  0  5  10
1  1  6  11
2  2  7  12
3  3  8  13
4  4  9  14

Масив після reshape(5, 3):

    0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14