# Завдання 6

In [ ]:
import numpy as np
import pandas as pd

first = np.arange(1, 6)
second = np.arange(6, 11)

combined = np.concatenate((first, second))
array_2x5 = np.vstack((first, second))
array_5x2 = np.column_stack((first, second))

print("Об'єднаний одновимірний масив:")
display(pd.DataFrame({"Значення": combined}))
print("Двовимірний масив 2 x 5:")
display(pd.DataFrame(array_2x5))
print("Двовимірний масив 5 x 2:")
display(pd.DataFrame(array_5x2))

Об'єднаний одновимірний масив:

   Значення
0         1
1         2
2         3
3         4
4         5
5         6
6         7
7         8
8         9
9        10

Двовимірний масив 2 x 5:

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

Двовимірний масив 5 x 2:

   0   1
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10